#------------------------------------------------------------------------
# Regression model generated by GeneXproTools 5.0 on 06-Nov-24 7:02:21 PM
# GEP File: E:\04- ML Works\03- Topic-23\Gep results\ML23.gep
# Training Records:  83
# Validation Records:   36
# Fitness Function:  RMSE
# Training R-square: 0.984417386306537
# Validation R-square:  0.945290698035142
#------------------------------------------------------------------------

from math import *

def gepModel(d):

	G1C15 = -0.56667032974307
	G1C3 = -4.45600756859035
	G1C13 = -5.5664398696366
	G1C4 = 3.84865819269387
	G2C6 = 0.61142135748598
	G2C10 = 6.13875698110904
	G3C15 = -2.07292754917462
	G3C0 = -4.95310921211484

	y = 0.0

	y = pow((G1C15*((G1C3-d[0]-G1C13)+pow(d[4],2.0)+(d[0]/G1C4))*pow(d[6],2.0)),3.0)
	y = y + ((pow(d[5],2.0)+G2C6+(d[0]+d[2]+d[4]))/(G2C10+(d[6]-d[1])+d[6]))
	y = y + pow((d[3]/(((d[0]+G3C0+d[2])+d[5])+(d[4]/G3C15)+pow(d[1],3.0))),2.0)

	return y
	

